import { UserProfile, Opportunity, Mission } from "./types";

export const initialProfile: UserProfile = {
  id: "usr_tomide_001",
  fullName: "Tomide Williams",
  email: "oppverseai@gmail.com",
  citizenship: ["Nigeria"],
  countryOfResidence: "Nigeria",
  city: "Lagos",
  yearsOfExperience: 6,
  careerLevel: "Senior",
  education: [
    {
      degree: "B.Sc. in Computer Science / Information Systems",
      institution: "University of Lagos",
      field: "Technology & Software Systems",
      graduationYear: "2019"
    }
  ],
  workHistory: [
    {
      role: "Founding GTM & Product Marketing Lead",
      company: "Conductor (Vera Pax Technologies)",
      location: "Remote",
      startDate: "Aug 2026",
      endDate: "Present",
      description: "Leading commercial engine, GTM positioning, demand generation, and time intelligence strategy."
    },
    {
      role: "Product Marketing Manager",
      company: "Koppoh",
      location: "Lagos, Nigeria",
      startDate: "2024",
      endDate: "2026",
      description: "Executed flagship course launch campaigns (BOP), creator growth funnels, and marketing systems."
    },
    {
      role: "AI Consultant & Systems Engineer",
      company: "Independent AI Consulting",
      location: "Remote",
      startDate: "2023",
      endDate: "Present",
      description: "Building autonomous agentic workflows, n8n orchestrations, and AI revenue operating systems for SMEs."
    }
  ],
  languages: ["English (Fluent)", "Yoruba (Native)"],
  skills: [
    "Product Marketing",
    "Go-To-Market Strategy",
    "AI Agent Workflows",
    "Demand Generation",
    "Claude Code & LLM Prompting",
    "n8n Automation",
    "Positioning & Messaging",
    "SaaS Growth",
    "Public Speaking"
  ],
  personas: [
    {
      id: "persona_pmm",
      name: "Product Marketing Leader",
      role: "Senior Product Marketing Manager / GTM Lead",
      headline: "Leading GTM strategy, positioning, and international SaaS growth",
      targetUniverses: ["Jobs", "Fellowships", "Conferences", "Speaking"],
      goals: [
        "Land high-impact international remote GTM / PMM leadership roles",
        "Secure fully funded international technology fellowships"
      ],
      skills: ["Product Marketing", "GTM Strategy", "Positioning", "SaaS Growth", "AI Tools"],
      isDefault: true
    },
    {
      id: "persona_founder",
      name: "Tech Founder & Builder",
      role: "Founder & AI Systems Architect",
      headline: "Building AI-powered opportunity intelligence and productivity infrastructure",
      targetUniverses: ["Grants", "Accelerators", "Competitions", "Fellowships", "Conferences"],
      goals: [
        "Secure non-dilutive startup grants and accelerator backing",
        "Expand international investor & ecosystem network"
      ],
      skills: ["AI Systems", "Product Strategy", "Venture Building", "System Architecture"]
    },
    {
      id: "persona_speaker",
      name: "Keynote Speaker & AI Educator",
      role: "Keynote Speaker & AI Cohort Instructor",
      headline: "Teaching agentic AI workflows and speaking at global tech summits",
      targetUniverses: ["Speaking", "Conferences", "Travel"],
      goals: [
        "Speak at major international AI and SaaS conferences with speaker travel funding",
        "Educate 10,000+ African professionals on agentic AI"
      ],
      skills: ["Public Speaking", "Curriculum Design", "AI Education", "Workshops"]
    }
  ],
  activePersonaId: "persona_pmm",
  selectedUniverses: ["Jobs", "Fellowships", "Scholarships", "Grants", "Conferences", "Travel", "Accelerators", "Speaking"],
  goals: [
    "Get an international remote PMM role paying global standard",
    "Secure fully funded international fellowship in technology & leadership",
    "Speak at European & American AI summits with travel funding",
    "Secure non-dilutive grant funding for AI startup projects"
  ],
  relocationPreference: false,
  remotePreference: "Remote",
  profileStrength: 88,
  createdAt: "2026-09-01T08:00:00Z",
  updatedAt: "2026-09-19T14:00:00Z"
};

export const sampleOpportunities: Opportunity[] = [
  {
    id: "opp_001",
    title: "Senior Product Marketing Manager (AI Products)",
    provider: "Synthesia AI",
    category: "Jobs",
    subcategory: "Product Marketing",
    summary: "Lead product marketing for Synthesia's next-generation enterprise video generation agent suite. Fully remote globally with flexible timezone overlap.",
    description: "Looking for an experienced PMM with a deep passion for agentic AI and product storytelling. You will own product launches, competitive messaging, and customer research.",
    officialSourceUrl: "https://synthesia.io/careers/senior-pmm",
    applicationUrl: "https://synthesia.io/apply/senior-pmm",
    deadline: "2026-10-15T23:59:59Z",
    locationType: "Remote",
    eligibleNationalities: ["All"],
    fundingStatus: "Paid",
    fundingAmount: "$120,000 - $155,000 / year",
    applicationComplexity: "Quick",
    requiredDocuments: ["Resume", "Portfolio / Launch Case Study"],
    experienceRequired: "4+ years in B2B SaaS Product Marketing",
    verificationStatus: "Verified",
    isFeatured: true,
    tags: ["Product Marketing", "AI", "Remote", "SaaS"],
    postedDate: "2026-09-18T10:00:00Z"
  },
  {
    id: "opp_002",
    title: "Berlin AI & Emerging Tech Leadership Fellowship",
    provider: "Robert Bosch Foundation & Techstars",
    category: "Fellowships",
    subcategory: "Leadership & Technology",
    summary: "Fully funded 6-month residency in Berlin for emerging technology leaders and founders from emerging markets.",
    description: "Provides full round-trip international travel, luxury apartment in Berlin-Mitte, €4,200 monthly living stipend, and direct access to European venture capital leaders.",
    officialSourceUrl: "https://bosch-stiftung.de/berlin-ai-fellowship",
    applicationUrl: "https://bosch-stiftung.de/apply/2026-cohort",
    deadline: "2026-10-08T23:59:59Z",
    locationType: "Physical",
    hostCountry: "Germany",
    hostCity: "Berlin",
    eligibleNationalities: ["All", "Nigeria", "Ghana", "Kenya", "South Africa", "Emerging Markets"],
    fundingStatus: "Fully Funded",
    fundingAmount: "€4,200/mo + Flight + Housing + Insurance",
    applicationComplexity: "Moderate",
    requiredDocuments: ["CV", "Motivation Statement (800 words)", "2 Reference Contacts"],
    experienceRequired: "3+ years in AI, Technology, or Growth",
    verificationStatus: "Verified",
    isFeatured: true,
    tags: ["Fully Funded", "Fellowship", "Berlin", "AI Leadership"],
    postedDate: "2026-09-17T14:30:00Z"
  },
  {
    id: "opp_003",
    title: "Google for Startups Africa AI Accelerator (Equity-Free $100K)",
    provider: "Google for Startups",
    category: "Grants",
    subcategory: "Startup Grant & Accelerator",
    summary: "Equity-free funding, $100K in Google Cloud credits, and 3 months of 1-on-1 mentorship with Google AI research teams.",
    description: "Designed for seed-stage African technology founders leveraging AI to solve continental and global problems.",
    officialSourceUrl: "https://startup.google.com/accelerator/africa",
    applicationUrl: "https://startup.google.com/apply-africa",
    deadline: "2026-10-20T23:59:59Z",
    locationType: "Hybrid",
    hostCountry: "Nigeria",
    hostCity: "Lagos",
    eligibleNationalities: ["African Countries", "Nigeria", "Ghana", "Kenya", "Rwanda", "South Africa"],
    fundingStatus: "Grant Award",
    fundingAmount: "$100,000 Equity-Free + Cloud Credits",
    applicationComplexity: "Heavy",
    requiredDocuments: ["Pitch Deck", "Demo Video", "Incorporation Documents", "Founder Bio"],
    verificationStatus: "Verified",
    isFeatured: true,
    tags: ["Grant", "Startups", "Google", "Equity-Free"],
    postedDate: "2026-09-16T09:00:00Z"
  },
  {
    id: "opp_004",
    title: "Call for Speakers: AI Product Summit London 2026",
    provider: "Product Led Alliance",
    category: "Speaking",
    subcategory: "Conference Keynote",
    summary: "Looking for practitioner speakers on 'Agentic AI & The Future of GTM Systems'. Full travel and accommodation covered for accepted international keynote speakers.",
    description: "Present to 1,500+ VP of Product and Product Marketing executives at ExCeL London. Complimentary VIP pass, speaker dinner, and flight stipend provided.",
    officialSourceUrl: "https://productledalliance.com/london-2026-speakers",
    applicationUrl: "https://productledalliance.com/submit-talk",
    deadline: "2026-09-30T23:59:59Z",
    locationType: "Physical",
    hostCountry: "United Kingdom",
    hostCity: "London",
    eligibleNationalities: ["All"],
    fundingStatus: "Fully Funded",
    fundingAmount: "Flight + Hotel + VIP Speaker Pass",
    applicationComplexity: "Quick",
    requiredDocuments: ["Session Abstract (300 words)", "Speaker Bio", "Past Video Clip"],
    verificationStatus: "Verified",
    isSerendipity: true,
    tags: ["Speaking", "London", "AI Product", "Funded Travel"],
    postedDate: "2026-09-18T16:00:00Z"
  },
  {
    id: "opp_005",
    title: "Mastercard Foundation Scholars Program (Oxford University)",
    provider: "Oxford University & Mastercard Foundation",
    category: "Scholarships",
    subcategory: "Master's Degree",
    summary: "Full scholarship covering 100% of Oxford University tuition fees, living expenses stipend (£19,237), and return flights from Africa.",
    description: "Available for African citizens with strong academic merit and demonstrable leadership commitment to societal transformation.",
    officialSourceUrl: "https://ox.ac.uk/admissions/graduate/fees-and-funding/mastercard",
    applicationUrl: "https://ox.ac.uk/apply/mastercard-scholarship",
    deadline: "2026-11-15T23:59:59Z",
    locationType: "Physical",
    hostCountry: "United Kingdom",
    hostCity: "Oxford",
    eligibleNationalities: ["African Countries", "Nigeria", "Ghana", "Kenya"],
    fundingStatus: "Fully Funded",
    fundingAmount: "100% Tuition + £19,237/yr Living Allowance",
    applicationComplexity: "Heavy",
    requiredDocuments: ["Transcripts", "Academic CV", "2 Academic References", "Personal Statement"],
    verificationStatus: "Verified",
    tags: ["Oxford", "Scholarship", "Fully Funded", "Mastercard"],
    postedDate: "2026-09-10T12:00:00Z"
  },
  {
    id: "opp_006",
    title: "UN Climate & AI Innovation Travel Grant (Geneva, Switzerland)",
    provider: "United Nations Environment Programme (UNEP)",
    category: "Travel",
    subcategory: "Summit Delegate Grant",
    summary: "Fully funded travel grant for 20 emerging market technology practitioners to attend the Global AI for Planet Forum in Geneva.",
    description: "Includes Swiss Schengen visa facilitation letter, round-trip economy flights, UN per diem accommodation allowance, and private bilateral roundtable sessions.",
    officialSourceUrl: "https://unep.org/ai-for-planet-geneva",
    applicationUrl: "https://unep.org/apply/travel-grant",
    deadline: "2026-10-04T23:59:59Z",
    locationType: "Physical",
    hostCountry: "Switzerland",
    hostCity: "Geneva",
    eligibleNationalities: ["All", "Nigeria", "Developing Nations"],
    fundingStatus: "Fully Funded",
    fundingAmount: "Flights + Visa Support + $2,800 UN Per Diem",
    applicationComplexity: "Moderate",
    requiredDocuments: ["Passport Copy", "CV", "Short Impact Essay (500 words)"],
    verificationStatus: "Verified",
    isFeatured: true,
    tags: ["United Nations", "Geneva", "Travel Grant", "AI Forum"],
    postedDate: "2026-09-15T08:00:00Z"
  },
  {
    id: "opp_007",
    title: "Web Summit Lisbon 2026 — Emerging Market Founder & Creator Fellowship",
    provider: "Web Summit & Enterprise Ireland",
    category: "Conferences",
    subcategory: "Global Tech Summit",
    summary: "Full conference VIP pass, exhibit booth access, investor match sessions, and €1,500 travel subsidy for top African & Global South innovators.",
    description: "Join 70,000+ tech leaders, founders, and investors in Lisbon. Includes exclusive access to Venture & Mentor Hours, PMM roundtables, and VIP opening night.",
    officialSourceUrl: "https://websummit.com/emerging-innovators-2026",
    applicationUrl: "https://websummit.com/apply/scholarship",
    deadline: "2026-10-12T23:59:59Z",
    locationType: "Physical",
    hostCountry: "Portugal",
    hostCity: "Lisbon",
    eligibleNationalities: ["All", "Nigeria", "African Countries", "Emerging Markets"],
    fundingStatus: "Fully Funded",
    fundingAmount: "Full VIP Pass (€1,850) + €1,500 Flight Grant",
    applicationComplexity: "Moderate",
    requiredDocuments: ["Founder/Practitioner Bio", "Product / Workflow Overview", "Passport Copy"],
    experienceRequired: "2+ years in Tech, Product, or AI Innovation",
    verificationStatus: "Verified",
    isFeatured: true,
    tags: ["Conferences", "Web Summit", "Lisbon", "Fully Funded", "AI & SaaS"],
    postedDate: "2026-09-19T09:00:00Z"
  },
  {
    id: "opp_008",
    title: "Global AI & Time Intelligence World Congress 2026",
    provider: "International AI Society & Vera Pax Research",
    category: "Conferences",
    subcategory: "AI Systems & Enterprise Tech",
    summary: "Flagship global conference exploring autonomous workflow agents, time intelligence, and modern GTM architectures.",
    description: "Featuring 200+ executive speakers from OpenAI, Anthropic, Google DeepMind, and fast-growing B2B SaaS startups. Special sponsored passes available for African practitioners.",
    officialSourceUrl: "https://aiworldcongress.org/2026",
    applicationUrl: "https://aiworldcongress.org/scholarships",
    deadline: "2026-10-25T23:59:59Z",
    locationType: "Hybrid",
    hostCountry: "United States",
    hostCity: "San Francisco / Virtual",
    eligibleNationalities: ["All"],
    fundingStatus: "Fully Funded",
    fundingAmount: "Complimentary All-Access Pass ($1,499) + Virtual Access",
    applicationComplexity: "Quick",
    requiredDocuments: ["LinkedIn Profile", "Short Motivation (200 words)"],
    experienceRequired: "Open to all technology professionals",
    verificationStatus: "Verified",
    tags: ["Conferences", "San Francisco", "AI Systems", "GTM"],
    postedDate: "2026-09-19T11:00:00Z"
  }
];

export const sampleMissions: Mission[] = [
  {
    id: "msn_01",
    title: "Remote PMM & GTM Roles at AI Startups",
    prompt: "Find senior product marketing and GTM roles at AI SaaS companies that allow remote work from Nigeria and pay global rates.",
    targetCategories: ["Jobs"],
    countries: ["Remote", "United States", "Europe"],
    fundingPreference: "Paid",
    isActive: true,
    matchCount: 8,
    lastRunAt: "2026-09-19T06:00:00Z",
    createdAt: "2026-09-01T10:00:00Z"
  },
  {
    id: "msn_02",
    title: "Fully Funded AI & Tech Leadership Fellowships",
    prompt: "Find fully funded international leadership fellowships in AI, technology, and public interest tech that are open to Nigerian applicants.",
    targetCategories: ["Fellowships", "Travel"],
    countries: ["Germany", "United Kingdom", "United States", "Global"],
    fundingPreference: "Fully Funded",
    isActive: true,
    matchCount: 5,
    lastRunAt: "2026-09-19T06:00:00Z",
    createdAt: "2026-09-02T14:00:00Z"
  },
  {
    id: "msn_03",
    title: "International AI Conference Speaking & Funded Passes",
    prompt: "Find calls for speakers and fully funded delegate conference passes for major European & US tech summits.",
    targetCategories: ["Speaking", "Conferences"],
    countries: ["Europe", "North America", "Middle East"],
    fundingPreference: "Fully Funded",
    isActive: true,
    matchCount: 4,
    lastRunAt: "2026-09-19T06:00:00Z",
    createdAt: "2026-09-05T09:30:00Z"
  }
];
